export const REACT_APP_MIDTRANS_SERVER_KEY = process.env.REACT_APP_MIDTRANS_SERVER_KEY
export const REACT_APP_MIDTRANS_CLIENT_KEY = process.env.REACT_APP_MIDTRANS_CLIENT_KEY

export const PAID = "PAID"
export const CANCELED ="CANCELED"
export const PENDING_PAYMENT ="PENDING_PAYMENT"