# Generated by Django 5.0.7 on 2024-08-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_profile_age_profile_bio_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
