# Generated by Django 5.0.7 on 2024-08-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_profile_age_profile_bio_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
