# Generated by Django 5.0.7 on 2024-08-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_remove_profile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
