# Generated by Django 5.0.7 on 2024-08-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
