# Generated by Django 5.0.7 on 2024-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0011_remove_profile_age_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
