# Generated by Django 5.0.7 on 2024-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_ind',
            field=models.TextField(null=True),
        ),
    ]
