# Generated by Django 5.0.7 on 2024-08-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activity_description_en_activity_description_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='long_description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='long_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='long_description_ind',
            field=models.TextField(null=True),
        ),
    ]
