# Generated by Django 5.0.7 on 2024-08-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
