# Generated by Django 5.0.8 on 2024-08-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_activity_latitude_activity_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description_ind',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='long_description_en',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='long_description_ind',
        ),
    ]
