# Generated by Django 5.0.8 on 2024-08-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_remove_activity_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_en',
            field=models.TextField(default='b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='description_id',
            field=models.TextField(default='c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='long_description_en',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='long_description_id',
            field=models.TextField(default='e'),
            preserve_default=False,
        ),
    ]
